[tool.ruff]
line-length = 100
target-version = "py311"

[tool.mypy]
python_version = "3.11"
strict = true
ignore_missing_imports = true
pretty = true
show_error_codes = true

[tool.pytest.ini_options]
addopts = "-q --maxfail=1"
